name: README auto commit

on:
  schedule:
    - cron: "0 0 * * *"
    - cron: "0 1 * * *"   
    - cron: "0 23 * * *"   
  workflow_dispatch:

permissions:
  contents: write

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Configure git
        run: |
          git config user.name "vishwajeet-singhh"
          git config user.email "vishwajeet.singh@mayadataprivacy.eu"

      - name: Update README
        run: |
          echo "update $(date) $RANDOM" >> README.md
          git add README.md
          git commit -m "auto update" || echo "no change"

      - name: Push
        run: |
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
